{% set name = "memray" %}
{% set version = "1.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48f8f9b89b3a84028668244151eb7248189fb3f4f2a761ec1211439adcbb2ad1

build:
  skip: true  # [win]
  script:
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - make
    - pkgconfig
  host:
    - elfutils  # [linux]
    - python
    - pip
    - pkgconfig
    - libunwind  # [linux]
    - cython
    - lz4-c
  run:
    - python
    - rich >=11.2.0
    - jinja2
    - textual >=0.34.0
    - typing-extensions  # [py<38]

test:
  imports:
    - memray
  requires:
    - pip
  commands:
    - pip check
    - memray -h

about:
  home: https://github.com/bloomberg/memray
  summary: Memray is a memory profiler for Python
  description: |
    Memray is a memory profiler for Python. It can track memory allocations in
    Python code, in native extension modules, and in the Python interpreter
    itself. It can generate several different types of reports to help you
    analyze the captured memory usage data. While commonly used as a CLI tool,
    it can also be used as a library to perform more fine-grained profiling
    tasks.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - src/vendor/libbacktrace/LICENSE
  doc_url: https://bloomberg.github.io/memray/
  dev_url: https://github.com/bloomberg/memray

extra:
  recipe-maintainers:
    - matthiasdiener
