{% set name = "memray" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e22ad913c46f7402c1eb0ac0b3e61cac43f4f1411fb987da492a71403317e45f

build:
  skip: true  # [win]
  script:
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - make
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - pip
    - libunwind  # [linux]
    - cython
    - lz4-c
  run:
    - python
    - rich
    - jinja2
    - typing-extensions  # [py<38]

test:
  imports:
    - memray
  requires:
    - pip
  commands:
    - pip check
    - memray -h

about:
  home: https://github.com/bloomberg/memray
  summary: Memray is a memory profiler for Python
  description: |
    Memray is a memory profiler for Python. It can track memory allocations in
    Python code, in native extension modules, and in the Python interpreter
    itself. It can generate several different types of reports to help you
    analyze the captured memory usage data. While commonly used as a CLI tool,
    it can also be used as a library to perform more fine-grained profiling
    tasks.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - src/vendor/libbacktrace/LICENSE
  doc_url: https://bloomberg.github.io/memray/
  dev_url: https://github.com/bloomberg/memray

extra:
  recipe-maintainers:
    - matthiasdiener
